### ISSUE TITLE
Update fontUrl properties

### ISSUE THREAD

**Issue by davelab6** [googlefonts/korean#10]
In setting the font families public, the gstatic URLs will change, so `app/constants/defaults.js` will need to be updated.

**Comment by rsheeter** [comment]
The families are public (https://fonts.google.com/?subset=korean); 18 of them [everything but Nanum*] will have shifted URL. IMHO don't worry about fixing this for a few days. Risk of new problems and no real upside.

**Comment by wonyoungso** [comment]
Will update this afternoon (SGT).

**Comment by wonyoungso** [comment]
Updated!
