### ISSUE TITLE
Add user study recruiting link

### ISSUE THREAD

**Issue by davelab6** [googlefonts/korean#19]
Let's add a link to offer users the opportunity to sign up as Google Fonts user study participants. Here's the link:

https://google.qualtrics.com/jfe/form/SV_3NMIMtX0F2zkakR?reserved=1&utm_source=Online&Q_Language=en&utm_medium=own_othr&utm_campaign=Gf-KDS&utm_term=0&utm_content=0&productTag=0&campaignDate=jul19&pType=gprod&referral_code=RL12665

**Comment by eroonkang** [comment]
@wonyoungso  I think a good place would be at the footer, so it reads as following:

— (EN)

> **Join Our Community**
> 
> We are working with designers around the world to produce best-in-class typeface designs that are made for the web. If you want to offer your own Korean font through Google Fonts, please contact @googlefonts.
> 
> This website is also open source. To report any issues, please visit github.com/googlefonts/korean
> 
> **Google Fonts user research program** →

— (KO)

> **Google Fonts에 참여하세요.**
> 
> Google Fonts는 전 세계의 디자이너와 함께 웹에서 손쉽게 사용할 수 있는 폰트를 개발합니다. Google Fonts와 이곳에 여러분이 제작한 한글 폰트를 제공하고 싶다면 언제든지 @googlefonts 앞으로 알려주세요.
> 
> 이 사이트의 소스는 github.com/googlefonts/korean에 공개되어 있습니다. 관련 문의는 이곳에 리포트를 남겨주세요.
> 
> **구글폰트 유저 리서치 프로그램** →

**Comment by wonyoungso** [comment]
Both are added in the footer!
