### ISSUE TITLE
Use Travis for continuous integration

### ISSUE THREAD

**Issue by davelab6** [googlefonts/korean#2]
Use Travis to run `npm run build` and push the results to the gh-pages branch :)

https://docs.travis-ci.com/user/deployment/pages/

**Comment by davelab6** [comment]
@eroonkang I guess this became out of scope? If so, please close :)

**Comment by wonyoungso** [comment]
@davelab6 I was trying to integrate but had no permission to add, as far as I remembered-And they were sending an email to asking the permission but not getting?

**Comment by eroonkang** [comment]
@davelab6 Yup, closing this for now.

**Comment by davelab6** [comment]
@wonyoungso aha, that makes sense, thanks for clarifying ):
